export function StatModal({ isOpen, onClose, stat }) {
  if (!isOpen || !stat) return null;

  const getStatDetails = () => {
    switch(stat.type) {
      case 'total':
        return {
          title: 'Total Insights Analysis',
          icon: '📊',
          color: 'blue',
          description: 'All insights generated by AI across all data sources.',
          details: [
            { label: 'Current Total', value: stat.data },
            { label: 'High Confidence', value: '2' },
            { label: 'Medium Confidence', value: '1' },
            { label: 'Low Confidence', value: '1' },
            { label: 'Growth Rate', value: '+12%' }
          ]
        };
      case 'avg':
        return {
          title: 'Average Confidence Analysis',
          icon: '📈',
          color: 'green',
          description: 'Overall AI confidence score across all insights.',
          details: [
            { label: 'Current Average', value: `${stat.data}%` },
            { label: 'Highest', value: '95%' },
            { label: 'Lowest', value: '45%' },
            { label: 'Trend', value: '+3%' }
          ]
        };
      case 'sources':
        return {
          title: 'Active Sources Analysis',
          icon: '🗄️',
          color: 'purple',
          description: 'Data sources currently providing insights.',
          details: [
            { label: 'Total Sources', value: stat.data || 3 },
            { label: 'PDF Documents', value: '2' },
            { label: 'SQL Databases', value: '1' },
            { label: 'Log Files', value: '1' }
          ]
        };
      default:
        return null;
    }
  };

  const details = getStatDetails();
  if (!details) return null;

  const colorClasses = {
    blue: 'from-blue-500 to-blue-600',
    green: 'from-green-500 to-green-600',
    purple: 'from-purple-500 to-purple-600'
  };

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto">
      <div 
        className="fixed inset-0 bg-black/50 backdrop-blur-md"
        onClick={onClose}
      />
      
      <div className="flex min-h-full items-center justify-center p-4">
        <div className="relative bg-white dark:bg-[#0F1219] rounded-2xl shadow-2xl max-w-2xl w-full border border-gray-200 dark:border-gray-800">
          
          <div className={`p-6 bg-gradient-to-r ${colorClasses[details.color]} rounded-t-2xl`}>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <span className="text-4xl">{details.icon}</span>
                <div>
                  <h2 className="text-2xl font-bold text-white">{details.title}</h2>
                  <p className="text-blue-100 mt-1">{details.description}</p>
                </div>
              </div>
              <button
                onClick={onClose}
                className="p-2 hover:bg-white/20 rounded-lg transition-colors text-white"
              >
                <span className="text-xl">✕</span>
              </button>
            </div>
          </div>
          
          <div className="p-6 space-y-6">
            <div className="grid grid-cols-2 gap-4">
              {details.details.map((item, idx) => (
                <div key={idx} className="bg-gray-50 dark:bg-[#1A1E26] p-4 rounded-xl border border-gray-200 dark:border-gray-800">
                  <p className="text-xs text-gray-500 dark:text-gray-400 mb-1">{item.label}</p>
                  <p className="text-2xl font-bold text-gray-900 dark:text-white">{item.value}</p>
                </div>
              ))}
            </div>

            <div className="bg-gray-50 dark:bg-[#1A1E26] p-6 rounded-xl border border-gray-200 dark:border-gray-800">
              <h3 className="text-sm font-medium text-gray-700 dark:text-gray-300 mb-3 flex items-center gap-2">
                <span>📌</span> AI Recommendation
              </h3>
              <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
                {stat.type === 'total' && "Your insights are growing. Consider adding more data sources to increase coverage."}
                {stat.type === 'avg' && stat.data < 70 && "Average confidence is moderate. Review low-confidence insights for data quality issues."}
                {stat.type === 'avg' && stat.data >= 70 && "Confidence levels are good. Continue monitoring for any drops in quality."}
                {stat.type === 'sources' && "You have multiple active sources. Ensure all connections are stable for continuous insights."}
              </p>
            </div>
          </div>
          
          <div className="flex items-center justify-end p-6 border-t border-gray-200 dark:border-gray-800">
            <button
              onClick={onClose}
              className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-medium rounded-lg transition-colors"
            >
              Close
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}